name: Release

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read   # to fetch the tag
      packages: write  # to publish the PyPI package
      id-token: write  # if you use other authentication
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # needed to get all tags for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools setuptools_scm twine

      - name: Build packages
        run: |
          python -m build --sdist --wheel

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
